services:
  mysql:
    image: mysql:8.0
    container_name: ems-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_DATABASE: ems
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ems-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./ems-backend
    container_name: ems-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ems?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
    ports:
      - "8081:8081"
    networks:
      - ems-network
    restart: always

  frontend:
    build: ./ems-frontend
    container_name: ems-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - ems-network

volumes:
  mysql_data:

networks:
  ems-network:
    driver: bridge
